language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t mkumar/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mkumar/docker-react npm run test
