language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t mkumar/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mkumar/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucker_name: "elasticbeanstalk-us-east-1-569737592240"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"    